IT-Cotato/11th-Troublog-BE

- .coderabbit.yaml
- .github/ISSUE_TEMPLATE/feature-request.md
* Closes #9
* 프로젝트 코드 리뷰 자동화를 위한 CodeRabbit 구성 추가
* 코드 품질을 일관되게 유지하고 개발 생산성을 향상시키기 위해 AI 기반 코드 리뷰 도구를 도입했습니다.
* 최근 Github Projects 를 도입하면서 불필요한 Issue 태그를 삭제했습니다.
* CodeRabbit의 리뷰를 모두 다 반영해야하는 것은 아니며, 변경 제안을 거부헤도 됩니다.
* AI 리뷰가 팀원의 리뷰를 대변하지는 않습니다. 
* 작업 내용을 요약, 코드 품질 검사로만 확인 예정이니 코드 작성 후에는 팀원들의 리뷰 계속해서 부탁드립니다.
* 없음
* Comment 작성 시 …
> [Feat] CodeRabbit 설정 및 도입

- .github/workflows/cd.yml
* Closes #17 
* CD 워크플로우에서 docker-compose.yml 파일 복사 실패 (tar 오류)
* CD/CI에서 Docker 빌드 중복
* CD 워크플로우에서 docker build/push 단계 제거
* deploy 단계에서 `actions/checkout@v4` 추가
* 없음
* docker-compose.yml 파일을 EC2로 복사하려는 과정 중 아래 에러 발생
* deploy job에 `actions/checkout@v4` 스텝 추가
```java
tar: Cowardly refusing to create an empty archive
```
* CI, CD 두 과정에서 같은 이미지를 두 번 빌드하고 푸시하는 문제 
* CD 워크플로우의 build job에서 docker build/push 제거 (CI에서만 수행)
* develop 브랜치 push 시 자동 배포가 정상 동작하는지 테스트 필요
* Reviewer 분들은 코드 리뷰 시 좋은 코드의 방향을 제시하되, 코드 …
> [Fix] CD 과정 오류 수정

- src/main/java/troublog/backend/domain/auth/controller/AuthController.java
- src/main/java/troublog/backend/domain/auth/service/AuthService.java
- src/main/java/troublog/backend/domain/user/controller/UserController.java
- src/main/java/troublog/backend/domain/user/converter/UserConverter.java
- src/main/java/troublog/backend/domain/user/dto/request/UserProfileUpdateReqDto.java
- src/main/java/troublog/backend/domain/user/dto/response/UserInfoResDto.java
- src/main/java/troublog/backend/domain/user/dto/response/UserProfileResDto.java
- src/main/java/troublog/backend/domain/user/entity/User.java
- src/main/java/troublog/backend/domain/user/service/UserFacade.java
- src/main/java/troublog/backend/domain/user/service/command/UserCommandService.java
- src/main/java/troublog/backend/domain/user/service/query/UserQueryService.java
- src/main/java/troublog/backend/domain/user/validator/UserValidator.java
- src/main/java/troublog/backend/global/common/error/ErrorCode.java
* Closes #25 
* 사용자정보 API를 개발했습니다.
* 사용자의 경우 `isDeleted` 칼럼을 추가해 soft-delete를 적용했습니다.
* 없음
* 없음
* UseCase단의 밸리데이션이나, 삭제된 데이터인지등을 검증하는 로직을 Validator클래스에 담아봤는데, 이에 대한 의견이 궁금합니다..!
*
* P2 : …
> [Feat] 사용자 정보 API 개발

- src/main/java/troublog/backend/global/common/config/CorsConfig.java
- src/main/java/troublog/backend/global/common/config/SecurityConfig.java
* Closes #
*
* Cors오류 해결
* 없음
*
*
---
> [Fix] Cors 오류 해결

- src/main/java/troublog/backend/domain/auth/controller/AuthController.java
- src/main/java/troublog/backend/domain/auth/dto/LoginResDto.java
- src/main/java/troublog/backend/domain/auth/service/AuthFacade.java
- src/main/java/troublog/backend/domain/auth/service/AuthService.java
- src/main/java/troublog/backend/global/common/config/SwaggerConfig.java
- src/main/resources/application-dev.yml
* Closes #
*
* CORS 해결 - swagger server수정
* AuthFacade 추가
* application-dev.yml 파일 추가
* .env파일 수정
* 없음
*
*
* P3 : 이런 방법도 있을 것 같아요~ 등의 사소한 의견입니다 …
> [Fix] cors수정 - swagger server수정

- src/main/java/troublog/backend/global/common/config/CorsConfig.java
* Closes #
* localhost 5173 추가
*
* 없음
*
*
---
> [Fix] localhost 5173 추가

- src/main/java/troublog/backend/domain/project/controller/ProjectController.java
- src/main/java/troublog/backend/domain/project/converter/ProjectConverter.java
- src/main/java/troublog/backend/domain/project/dto/request/ProjectReqDto.java
- src/main/java/troublog/backend/domain/project/dto/response/ProjectDetailResDto.java
- src/main/java/troublog/backend/domain/project/dto/response/ProjectResDto.java
- src/main/java/troublog/backend/domain/project/entity/Project.java
- src/main/java/troublog/backend/domain/project/enums/ProjectPostStatus.java
- src/main/java/troublog/backend/domain/project/repository/ProjectRepository.java
- src/main/java/troublog/backend/domain/project/service/command/ProjectCommandService.java
- src/main/java/troublog/backend/domain/project/service/facade/ProjectCommandFacade.java
- src/main/java/troublog/backend/domain/project/service/facade/ProjectQueryFacade.java
- src/main/java/troublog/backend/domain/project/service/factory/ProjectFactory.java
- src/main/java/troublog/backend/domain/project/service/query/ProjectQueryService.java
- src/main/java/troublog/backend/domain/statistics/controller/StatisticsController.java
- src/main/java/troublog/backend/domain/trouble/controller/PostQueryController.java
- src/main/java/troublog/backend/domain/trouble/converter/ListConverter.java
- src/main/java/troublog/backend/domain/trouble/dto/response/TroubleListResDto.java
- src/main/java/troublog/backend/domain/trouble/enums/SortType.java
- src/main/java/troublog/backend/domain/trouble/enums/VisibilityType.java
- src/main/java/troublog/backend/domain/trouble/repository/PostRepository.java
- src/main/java/troublog/backend/domain/trouble/service/facade/PostQueryFacade.java
- src/main/java/troublog/backend/domain/trouble/service/query/PostQueryService.java
* Closes #38 
* Project 도메인 설계, 관련 기능 구현
* 트러블슈팅 필터링 조회 기능 구현
* 프로젝트 내 트러블슈팅 목록 조회의 경우 project 패키지 내에서 Facede까지, post 패키지에서 service 코드로 설계했습니다
*
* 중요도 순 정렬시 postRepository에서 직접 int와 case로 매핑시키고 있는 데 더 좋은 방법이 있으면 추천 부탁드립니다..
* P1 : 꼭 반영해 주세요 (Request …
> [Feat] 프로젝트 생성, 트러블슈팅 조회 API 개발

- src/main/java/troublog/backend/domain/trouble/controller/PostCommandController.java
- src/main/java/troublog/backend/domain/trouble/controller/PostQueryController.java
* Closes #66
* 기존에 구현한 자신의 트러블슈팅 목록 조회와 검색 로직을 기반으로 특정 `userId`를 기반으로 한 트러블 슈팅 목록 조회와 검색을 구현했습니다.
*  변경 `/my` -> `/my/search`
*  변경 `/list` -> `/my/list`
*  추가 `/users/{userId}/search`
* 추가  `/users/{userId}/list`
* 트러블슈팅 문서의 soft delete와 복구 api를 `@Deprecated` 처리했습니다.
* 현재 조회시 특정 사용자의 트러블 슈팅 요약본도 보입니다. 다음 이슈에서 분리 작업을 진행할 예정이라 해당 작업에서 수정하지 않았습니다. 
* 없음
* Review는 특수한 케이스가 아니면 Reviewer로 지정된 시점 …
> [Feat] 사용자 ID 기반 트러블슈팅 목록 조회 및 검색 기능 추가

- src/main/java/troublog/backend/domain/trouble/controller/CommunityController.java
- src/main/java/troublog/backend/domain/trouble/converter/CommentConverter.java
- src/main/java/troublog/backend/domain/trouble/dto/response/CommentResDto.java
- src/main/java/troublog/backend/domain/trouble/entity/Comment.java
- src/main/java/troublog/backend/domain/trouble/repository/PostRepository.java
- src/main/java/troublog/backend/domain/trouble/service/facade/command/RecentPostCommandFacade.java
- src/main/java/troublog/backend/domain/trouble/service/facade/query/PostQueryFacade.java
- src/main/java/troublog/backend/domain/trouble/service/query/PostQueryService.java
- src/main/java/troublog/backend/domain/trouble/service/query/RecentPostQueryService.java
* Closes #70 
* Redis ZSET을 활용한 최근열람 기능을 추가했습니다
* TTL 7일 설정 -  매 열람 시 리스트의 TTL 갱신
* 커뮤니티 댓글 응답 필드 추가
* 부모 댓글 모두 null로 뜨는 오류 수정
*
* 최근 열람 기록을 저장하는 과정에 대해서 현재는 커뮤니티 내 트러블 슈팅 상세 조회 API(/community/{postId} 호출 시 갱신되게 했습니다
*
* P1 : 꼭 반영해 주세요 (Request …
> [Refactor] 커뮤니티 응답 수정, 최근 열람 조회 API 추가

- src/main/java/troublog/backend/global/common/config/SwaggerConfig.java
* Closes #75
* Swagger dev 서버 주소를 도메인 주소로 변경
* 위와 동일
* 없음 
* 없음
* 없음
---
> [Config]서버 HTTPS 적용으로 인한 Swagger 설정 변경

- src/main/java/troublog/backend/global/common/config/CorsConfig.java
* Closes #75
* corsfilter에 도메인 주소 추가
* 위와 동일 
* 없음
* 없음
* 없음
---
> 🔧 [Config] CORS 허용 도메인에 서버 도메인 추가

- src/main/java/troublog/backend/domain/auth/service/AuthFacade.java
- src/main/java/troublog/backend/domain/trouble/controller/CommunityController.java
- src/main/java/troublog/backend/domain/trouble/repository/PostRepository.java
- src/main/java/troublog/backend/domain/trouble/service/facade/query/PostQueryFacade.java
- src/main/java/troublog/backend/domain/trouble/service/query/PostQueryService.java
- src/main/java/troublog/backend/domain/user/controller/UserController.java
- src/main/java/troublog/backend/domain/user/converter/UserConverter.java
- src/main/java/troublog/backend/domain/user/dto/response/UserInfoResDto.java
- src/main/java/troublog/backend/domain/user/dto/response/UserPostStatusResDto.java
- src/main/java/troublog/backend/domain/user/service/UserFacade.java
- src/main/java/troublog/backend/domain/user/service/query/FollowQueryService.java
- src/main/java/troublog/backend/domain/user/service/query/UserQueryService.java
- src/main/java/troublog/backend/domain/user/validator/UserValidator.java
- src/main/java/troublog/backend/global/common/error/ErrorCode.java
* Closes #65 
* 수이님 요청으로 사용자 트러블 슈팅을 작성상태 별로 가져오는 api 구현했습니다
* 인증 과정, 유저 조회 시 유저의 status 가 ACTIVE 인 유저만 조회하도록 수정했습니다. (유저의 상태는 INCOMPLETE, ACTIVE)로 나뉘는데, 소셜 로그인 과정에서 유저를 임시 저장하는 로직이 필요해 status가 추가되었습니다.
*
* 없음
*
*
* P1 : 꼭 반영해 주세요 (Request Changes) - …
> [Refactor] 사용자 관리 api 수정 및 리팩토링

- src/main/java/troublog/backend/global/common/config/CorsConfig.java
* Closes #78 
* 프론트 cors 설정
*
* 없음
*
*
---
> [Fix] 프론트 도메인 cors 설정

- src/main/java/troublog/backend/global/common/util/JwtProvider.java
> [Fix] setcookie secure설정

- src/main/java/troublog/backend/domain/trouble/converter/PostConverter.java
- src/main/java/troublog/backend/domain/trouble/dto/request/PostReqDto.java
- src/main/java/troublog/backend/domain/trouble/dto/response/PostResDto.java
- src/main/java/troublog/backend/domain/trouble/entity/Post.java
- src/main/java/troublog/backend/domain/trouble/enums/TemplateType.java
- src/main/java/troublog/backend/domain/trouble/service/facade/query/PostQueryFacade.java
- src/main/java/troublog/backend/domain/trouble/service/facade/relation/PostRelationFacade.java
* Closes #91
* 누락된 좋아요 수 기준 정렬 기능을 복구했습니다.
* 좋아요 수 기반 정렬 기능 추가
* 요약 완료시 PostStatus가 정상적으로 업데이트 되도록 수정
* 트러블슈팅 문서의 작성 템플릿 구분을 위한 `TemplateType` 컬럼 추가
* 없음
* 없음
* P2 : 반영을 적극적으로 고려해 주시면 좋을 것 …
> [Fix] 커뮤니티 게시글 목록 좋아요 기준 정렬 기능 수정

- src/main/java/troublog/backend/domain/alert/converter/AlertConverter.java
- src/main/java/troublog/backend/domain/alert/dto/response/AlertResDto.java
- src/main/java/troublog/backend/domain/alert/entity/Alert.java
- src/main/java/troublog/backend/domain/auth/service/AuthFacade.java
- src/main/java/troublog/backend/domain/trouble/controller/CommunityController.java
- src/main/java/troublog/backend/domain/trouble/service/facade/command/CommentCommandFacade.java
- src/main/java/troublog/backend/domain/trouble/service/facade/command/LikeCommandFacade.java
- src/main/java/troublog/backend/global/common/config/CorsConfig.java
- src/main/java/troublog/backend/global/common/constant/Domain.java
* Closes #89 
* 알림 targetUrl 설정, 이를 위한 Domain enum추가
*
* 없음
*
*
---
> [Fix] Domain enum추가, 알림 targetUrl 추가

- src/main/java/troublog/backend/domain/trouble/converter/ListConverter.java
*
* 내 트러블슈팅 조회 시 StarRating이 누락되어 추가했습니다
*
*
*
---
> [Chore] 내 트러블슈팅 조회 API 중요도 필드 추가

- src/main/java/troublog/backend/domain/statistics/repository/StatisticsRepository.java
*
* 기존에는 completed_at만을 기준으로 하여 일일 통계가 기능명세서 기준에 맞지 않아, 남긴 트러블 슈팅 개수에 따라 활동을 측정하기 위해 updated_at을 통계 기준에 포함했습니다
*
*
*
* P3 : 이런 방법도 있을 것 같아요~ 등의 …
> [Fix] updated_at 일일 활동 통계 기준에 포함

- src/main/java/troublog/backend/domain/image/controller/ImageController.java
- src/main/java/troublog/backend/domain/image/service/facade/ImageFacade.java
- src/main/java/troublog/backend/domain/image/service/s3/S3Uploader.java
- src/main/java/troublog/backend/global/common/config/SecurityConfig.java
* Closes #103
* 기존 이미지 업로드 시 유저 인증 절차를 제외했습니다.
* 임시 폴더인 `test/` 에 이미지가 저장되도록 변경했습니다.
* 없음
* 없음
* 없음
* 없음
* P3 : 이런 방법도 있을 것 같아요~ 등의 사소한 의견입니다 …
> [Config] Security 설정 변경

- .github/workflows/cd.yml
- .github/workflows/ci.yml
* Closes #
* main branch로 배포 진행
*
*
* 
*
---
> [Deploy] main branch 배포 진행 

- src/main/java/troublog/backend/domain/auth/dto/OAuth2RegisterReqDto.java
- src/main/java/troublog/backend/domain/auth/service/AuthFacade.java
- src/main/java/troublog/backend/global/common/error/ErrorCode.java
> [Fix] 소셜로그인 dto, errorcode수정
